Git Branching Commands
skyvar/self-learning pull request #16
Opened 2023-03-22 12:23 UTC by RivkaZishinski

presentation on the subject:
Git Branching Commands
with sub-subjects:
  - `git rebase`.
  - `git checkout`. 
  - `git commit`.
  - `git merge`
  - `git merge --squash`.
  - `git reset`.
  - Multiple upstream.
  - Merge conflicts and resolution.
  - Git's branch system.

2023-03-22 15:05 UTC, bdsoha commented
Please add a mention to your issue in the description *(i.e. `Closes #2`)*.

2023-03-23 05:49 UTC, bdsoha commented
> Please add a mention to your issue in the description _(i.e. `Closes #2`)_.

@RivkaZishinski What is with this?

2023-03-23 06:13 UTC, RivkaZishinski commented
thank.
we did it.

2023-03-23 06:15 UTC, bdsoha commented
> thank. we did it.

Use reactions instead of comments.

2023-03-23 08:24 UTC, RivkaZishinski commented
We saw the additional tasks in discussions and we need to end the sub-subjects:
Multiple upstream.
and 3 level of reset
We are currently in the middle of working on both.

2023-03-26 06:02 UTC, RivkaZishinski commented
We marked our task, we move to review .

2023-03-26 06:18 UTC, RivkaZishinski commented on research-git branching-commands/CompetingConflicts.md
> +=============================================
############################################

2023-03-26 06:58 UTC, ShaindyBorzikowsky requested changes
```bash
git commit -a.
```

2023-03-26 07:00 UTC, ShaindyBorzikowsky requested changes
```bash
git commit -m
```

2023-03-26 07:06 UTC, ShaindyBorzikowsky approved these changes

2023-03-26 07:52 UTC, ShaindyBorzikowsky commented on research-git branching-commands/commit.md
> +git commit -a. Commit a snapshot of all changes in the working directory. This only includes modifications to tracked files (those that have been added with git add at some point in their history). g
```suggestion
`git commit -a.` Commit a snapshot of all changes in the working directory. This only includes modifications to tracked files (those that have been added with git add at some point in their history). `git commit -m` "commit message" A shortcut command that immediately creates a commit with a passed commit message
```

2023-03-26 08:29 UTC, ShaindyBorzikowsky commented on research-git branching-commands/commit.md
> +   ![commit1](images/commit1.png)
There is no explanation of the meaning of the screenshots

2023-03-26 08:33 UTC, RivkaZishinski commented on research-git branching-commands/commit.md
> +   ![commit1](images/commit1.png)
1. There was no such requirement.
 2. After reading the document the picture is absolutely clear.

2023-03-26 09:28 UTC, ShaindyBorzikowsky commented on research-git branching-commands/mergeSquash.md
> +- every commit is "green" and so tools like git   bisect can be used, and any commit can be deployed with confidence?
```suggestion
- every commit is "green" and so tools like git   bisect can be used, and any commit can be deployed with confidence
```

2023-03-26 09:28 UTC, ShaindyBorzikowsky commented on research-git branching-commands/mergeSquash.md
> +It seems clear that if a project is trying to onboard a lot of developers who are not so confident with git then requiring squashing (using git rebase) is going to be an extra barrier for those devel
The summary is exhaustive and clear. However, it is recommended to place it as a summary of the three types of merger rather than as a summary of this specific topic.
Good luck!

2023-03-26 10:45 UTC, RivkaZishinski commented
we think that we end the code review - can we merge the PR?

2023-03-27 04:03 UTC, merged

2023-03-27 04:38 UTC, bdsoha commented
> we think that we end the code review - can we merge the PR?

If you are the *reviewer*, then you take upon yourself the responsibility of merging.
There are implication to be a *reviewer*: if in the future a *bug* or other issue is found, it is the joint responsibility of the *author* and the *reviewer* to resolve.